# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BDDTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BDDTest
    pod 'Quick'
    pod 'Nimble'
  target 'BDDTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BDDTestUITests' do
    # Pods for testing
  end

end
